I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 116, in script call
    call scene2
  File "game/script.rpy", line 322, in script
    gg "-Конечно, сначала нужна завязка, потом развитие, а потом в момент кульминации мы увидим хакеров."
KeyError: 'viname'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 116, in script call
    call scene2
  File "game/script.rpy", line 322, in script
    gg "-Конечно, сначала нужна завязка, потом развитие, а потом в момент кульминации мы увидим хакеров."
  File "S:\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "S:\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "S:\renpy-8.1.3-sdk\renpy\character.py", line 1335, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "S:\renpy-8.1.3-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "S:\renpy-8.1.3-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "S:\renpy-8.1.3-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "S:\renpy-8.1.3-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'viname'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
hacker secrets 1.0
Sun Dec 31 18:35:40 2023
